conversion:
  Alsace Descente: Vallée de Munster Descente
  Alsace Forêt: Forêt de Saverne
  Alsace La Mossig: La traversée de La Mossig
  Alsace Luttenbach: Luttenbach près Munster
  Alsace Montée: Vallée de Munster Montée
  Alsace Obersteigen: Obersteigen
  Alsace Petit Ballon: Col du petit Ballon
  Alsace Sommet: Sommet de Munster
  Alsace Steigenbach: Steigenbach
  Alsacia Descente: Vallée de Munster Descente
  Alsacia Forêt: Forêt de Saverne
  Alsacia La Mossig: La traversée de La Mossig
  Alsacia Luttenbach: Luttenbach près Munster
  Alsacia Montée: Vallée de Munster Montée
  Alsacia Obersteigen: Obersteigen
  Alsacia Petit Ballon: Col du petit Ballon
  Alsacia Sommet: Sommet de Munster
  Alsacia Steigenbach: Steigenbach
  Alsazia Descente: Vallée de Munster Descente
  Alsazia Forêt: Forêt de Saverne
  Alsazia La Mossig: La traversée de La Mossig
  Alsazia Luttenbach: Luttenbach près Munster
  Alsazia Montée: Vallée de Munster Montée
  Alsazia Obersteigen: Obersteigen
  Alsazia Petit Ballon: Col du petit Ballon
  Alsazia Sommet: Sommet de Munster
  Alsazia Steigenbach: Steigenbach
  Gales Afon Bidno: Afon Bidno - Severn
  Gales Afon Biga: Afon Biga - Cwmbiga
  Gales Banc Gwyn: Banc Gwyn - Afon Biga
  Gales Bosque de Hafren: Cwmbiga - Fedw Fain
  Gales Cwmbiga: Cwmbiga - Afon Biga
  Gales Fedw Fain: Fedw Fain - Cwmbiga
  Gales Ospreys: Afon Biga - Banc Gwyn
  Gales Severn: Severn - Afon Bidno
  Galles Afon Bidno: Afon Bidno - Severn
  Galles Afon Biga: Afon Biga - Cwmbiga
  Galles Banc Gwyn: Banc Gwyn - Afon Biga
  Galles Cwmbiga: Cwmbiga - Afon Biga
  Galles Fedw Fain: Fedw Fain - Cwmbiga
  Galles Foresta di Hafren: Cwmbiga - Fedw Fain
  Galles Ospreys: Afon Biga - Banc Gwyn
  Galles Severn: Severn - Afon Bidno
  Grecia Aghii Theodori: Aghii Theodori
  Grecia Aghii Theodori - Loutraki: Aghii Theodori - Loutraki
  Grecia Aghii Theodori al contrar: Aghii Theodori Reverse
  Grecia Aghii Theodori al contrario: Aghii Theodori Reverse
  Grecia Aghii Theodori inverso: Aghii Theodori Reverse
  Grecia Elatia: Elatia
  Grecia Elatia - Zeli: Elatia - Zeli
  Grecia Elatia al contrario: Elatia Reverse
  Grecia Elatia inverso: Elatia Reverse
  Grecia Loutraki - Aghii Theodori: Loutraki - Aghii Theodori
  Grecia New Loutraki: New Loutraki
  Grecia New Loutraki al contrario: New Loutraki Reverse
  Grecia Nuevo Loutraki: New Loutraki
  Grecia Nuevo Loutraki inverso: New Loutraki Reverse
  Grecia Zeli: Zeli
  Grecia Zeli - Elatia: Zeli - Elatia
  Grecia Zeli Inversa: Zeli Reverse
  Grecia Zeli inverso: Zeli Reverse
  Greece Aghii Theodori: Aghii Theodori
  Greece Aghii Theodori - Loutraki: Aghii Theodori - Loutraki
  Greece Aghii Theodori Reverse: Aghii Theodori Reverse
  Greece Elatia: Elatia
  Greece Elatia - Zeli: Elatia - Zeli
  Greece Elatia Reverse: Elatia Reverse
  Greece Loutraki - Aghii Theodori: Loutraki - Aghii Theodori
  Greece New Loutraki: New Loutraki
  Greece New Loutraki Reverse: New Loutraki Reverse
  Greece Zeli: Zeli
  Greece Zeli - Elatia: Zeli - Elatia
  Greece Zeli Reverse: Zeli Reverse
  Griechenland Aghii Theodori: Aghii Theodori
  Griechenland Aghii Theodori - Lo: Aghii Theodori - Loutraki
  Griechenland Aghii Theodori - Loutraki: Aghii Theodori - Loutraki
  Griechenland Aghii Theodori Rüc: Aghii Theodori Reverse
  Griechenland Aghii Theodori Rück: Aghii Theodori Reverse
  Griechenland Aghii Theodori Rückwärts: Aghii Theodori Reverse
  Griechenland Elatia: Elatia
  Griechenland Elatia - Zeli: Elatia - Zeli
  Griechenland Elatia Rückwärts: Elatia Reverse
  Griechenland Loutraki - Aghii Th: Loutraki - Aghii Theodori
  Griechenland Loutraki - Aghii Theodori: Loutraki - Aghii Theodori
  Griechenland Neues Loutraki: New Loutraki
  Griechenland Neues Loutraki Rüc: New Loutraki Reverse
  Griechenland Neues Loutraki Rück: New Loutraki Reverse
  Griechenland Neues Loutraki Rückwärts: New Loutraki Reverse
  Griechenland Zeli: Zeli
  Griechenland Zeli - Elatia: Zeli - Elatia
  Griechenland Zeli Rückwärts: Zeli Reverse
  Grèce Aghii Theodori: Aghii Theodori
  Grèce Aghii Theodori - Loutraki: Aghii Theodori - Loutraki
  Grèce Aghii Theodori inversé: Aghii Theodori Reverse
  Grèce Elatia: Elatia
  Grèce Elatia - Zeli: Elatia - Zeli
  Grèce Elatia inversé: Elatia Reverse
  Grèce Loutraki - Aghii Theodori: Loutraki - Aghii Theodori
  Grèce Nouveau Loutraki: New Loutraki
  Grèce Nouveau Loutraki inversé: New Loutraki Reverse
  Grèce Zeli: Zeli
  Grèce Zeli - Elatia: Zeli - Elatia
  Grèce Zeli inversé: Zeli Reverse
  Monte Carlo La Bollène: La Bollène-Vésubie - Peïra Cava
  Monte Carlo Mézien - Sisteron: Mézien - Sisteron
  Monte Carlo Mézien - St. Geniez: Mézien - St. Geniez
  Monte Carlo Peïra Cava: Peïra Cava - La Bollène-Vésubie
  Monte Carlo Peïra Cava - Turini: Peïra Cava - Turini
  Monte Carlo Peïra Cava – Tur: Peïra Cava - Turini
  Monte Carlo Peïra Cava – Turini: Peïra Cava - Turini
  Monte Carlo Pra d'Alart: Pra d'Alart
  Monte Carlo Sisteron - Mézien: Sisteron - Mézien
  Monte Carlo Sisteron - St. Genie: Sisteron - St. Geniez
  Monte Carlo Sisteron - St. Geniez: Sisteron - St. Geniez
  Monte Carlo Sommet de Turini: Sommet de Turini
  Monte Carlo St. Geniez - Mézien: St. Geniez - Mézien
  Monte Carlo St. Geniez - Sistero: St. Geniez - Sisteron
  Monte Carlo St. Geniez - Sisteron: St. Geniez - Sisteron
  Monte Carlo Turini - Peïra Cava: Turini - Peïra Cava
  Monte Carlo Turini Descente: Turini - La Bollène-Vésubie
  Monte Carlo Turini Montée: La Bollène-Vésubie - Turini
  Monte Carlo Turini –Peïra Ca: Turini - Peïra Cava
  Monte Carlo Turini –Peïra Cava: Turini - Peïra Cava
  Monte-Carlo La Bollène: La Bollène-Vésubie - Peïra Cava
  Monte-Carlo Mézien - Sisteron: Mézien - Sisteron
  Monte-Carlo Mézien - St. Geniez: Mézien - St. Geniez
  Monte-Carlo Peïra Cava: Peïra Cava - La Bollène-Vésubie
  Monte-Carlo Peïra Cava - Turini: Peïra Cava - Turini
  Monte-Carlo Pra d'Alart: Pra d'Alart
  Monte-Carlo Sisteron - Mézien: Sisteron - Mézien
  Monte-Carlo Sisteron - St. Genie: Sisteron - St. Geniez
  Monte-Carlo Sisteron - St. Geniez: Sisteron - St. Geniez
  Monte-Carlo Sommet de Turini: Sommet de Turini
  Monte-Carlo St. Geniez - Mézien: St. Geniez - Mézien
  Monte-Carlo St. Geniez - Sistero: St. Geniez - Sisteron
  Monte-Carlo St. Geniez - Sisteron: St. Geniez - Sisteron
  Monte-Carlo Turini - Peïra Cava: Turini - Peïra Cava
  Monte-Carlo Turini Descente: Turini - La Bollène-Vésubie
  Monte-Carlo Turini Montée: La Bollène-Vésubie - Turini
  Montecarlo La Bollène: La Bollène-Vésubie - Peïra Cava
  Montecarlo Mézien - Sisteron: Mézien - Sisteron
  Montecarlo Mézien - St. Geniez: Mézien - St. Geniez
  Montecarlo Peïra Cava: Peïra Cava - La Bollène-Vésubie
  Montecarlo Peïra Cava - Turini: Peïra Cava - Turini
  Montecarlo Pra d'Alart: Pra d'Alart
  Montecarlo Sisteron - Mézien: Sisteron - Mézien
  Montecarlo Sisteron - St. Geniez: Sisteron - St. Geniez
  Montecarlo Sommet de Turini: Sommet de Turini
  Montecarlo St. Geniez - Mézien: St. Geniez - Mézien
  Montecarlo St. Geniez - Sisteron: St. Geniez - Sisteron
  Montecarlo Turini - Peïra Cava: Turini - Peïra Cava
  Montecarlo Turini Descente: Turini - La Bollène-Vésubie
  Montecarlo Turini Montée: La Bollène-Vésubie - Turini
  Pays de Galles Afon Bidno: Afon Bidno - Severn
  Pays de Galles Afon Biga: Afon Biga - Cwmbiga
  Pays de Galles Banc Gwyn: Banc Gwyn - Afon Biga
  Pays de Galles Cwmbiga: Cwmbiga - Afon Biga
  Pays de Galles Fedw Fain: Fedw Fain - Cwmbiga
  Pays de Galles Hafren Forest: Cwmbiga - Fedw Fain
  Pays de Galles Ospreys: Afon Biga - Banc Gwyn
  Pays de Galles Severn: Severn - Afon Bidno
  Wales Afon Bidno: Afon Bidno - Severn
  Wales Afon Biga: Afon Biga - Cwmbiga
  Wales Banc Gwyn: Banc Gwyn - Afon Biga
  Wales Cwmbiga: Cwmbiga - Afon Biga
  Wales Fedw Fain: Fedw Fain - Cwmbiga
  Wales Hafren Forest: Cwmbiga - Fedw Fain
  Wales Ospreys: Afon Biga - Banc Gwyn
  Wales Severn: Severn - Afon Bidno
  威尔士 Afon Bidno: Afon Bidno - Severn
  威尔士 Afon Biga: Afon Biga - Cwmbiga
  威尔士 Banc Gwyn: Banc Gwyn - Afon Biga
  威尔士 Cwmbiga: Cwmbiga - Afon Biga
  威尔士 Fedw Fain: Fedw Fain - Cwmbiga
  威尔士 Ospreys: Afon Biga - Banc Gwyn
  威尔士 Severn: Severn - Afon Bidno
  威尔士 哈夫伦森林: Cwmbiga - Fedw Fain
  希腊 卢特拉基 - 阿吉伊: Loutraki - Aghii Theodori
  希腊 卢特拉基 - 阿吉伊西奥多里: Loutraki - Aghii Theodori
  希腊 埃拉蒂亚: Elatia
  希腊 埃拉蒂亚 - 泽利: Elatia - Zeli
  希腊 埃拉蒂亚反向: Elatia Reverse
  希腊 新卢特拉基: New Loutraki
  希腊 新卢特拉基反向: New Loutraki Reverse
  希腊 泽利: Zeli
  希腊 泽利 - 埃拉蒂亚: Zeli - Elatia
  希腊 泽利反向: Zeli Reverse
  希腊 阿吉伊西奥多里: Aghii Theodori
  '希腊 阿吉伊西奥多里 - ': Aghii Theodori - Loutraki
  希腊 阿吉伊西奥多里 - 卢特拉基: Aghii Theodori - Loutraki
  希腊 阿吉伊西奥多里反: Aghii Theodori Reverse
  希腊 阿吉伊西奥多里反向: Aghii Theodori Reverse
  蒙特卡洛 佩拉卡瓦: Peïra Cava - La Bollène-Vésubie
  蒙特卡洛 佩拉卡瓦 - 图: Peïra Cava - Turini
  蒙特卡洛 佩拉卡瓦 - 图里尼: Peïra Cava - Turini
  蒙特卡洛 图里尼 - 佩拉: Turini - Peïra Cava
  蒙特卡洛 图里尼 - 佩拉卡瓦: Turini - Peïra Cava
  蒙特卡洛 图里尼下山赛: Turini - La Bollène-Vésubie
  蒙特卡洛 图里尼山顶: Sommet de Turini
  蒙特卡洛 图里尼爬山赛: La Bollène-Vésubie - Turini
  蒙特卡洛 圣热尼 - 梅济: St. Geniez - Mézien
  蒙特卡洛 圣热尼 - 梅济安: St. Geniez - Mézien
  蒙特卡洛 圣热尼 - 锡斯: St. Geniez - Sisteron
  蒙特卡洛 圣热尼 - 锡斯特龙: St. Geniez - Sisteron
  蒙特卡洛 拉博莱讷: La Bollène-Vésubie - Peïra Cava
  蒙特卡洛 普拉阿尔特: Pra d'Alart
  蒙特卡洛 梅济安 - 圣热: Mézien - St. Geniez
  蒙特卡洛 梅济安 - 圣热尼: Mézien - St. Geniez
  蒙特卡洛 梅济安 - 锡斯: Mézien - Sisteron
  蒙特卡洛 梅济安 - 锡斯特龙: Mézien - Sisteron
  蒙特卡洛 锡斯特龙 - 圣: Sisteron - St. Geniez
  蒙特卡洛 锡斯特龙 - 圣热尼: Sisteron - St. Geniez
  蒙特卡洛 锡斯特龙 - 梅: Sisteron - Mézien
  蒙特卡洛 锡斯特龙 - 梅济安: Sisteron - Mézien
  阿尔萨斯 Mossig 河: La traversée de La Mossig
  阿尔萨斯 Obersteigen: Obersteigen
  阿尔萨斯 下山赛: Vallée de Munster Descente
  阿尔萨斯 吕滕巴赫: Luttenbach près Munster
  阿尔萨斯 小巴隆: Col du petit Ballon
  阿尔萨斯 山顶: Sommet de Munster
  阿尔萨斯 施泰因巴赫: Steigenbach
  阿尔萨斯 森林: Forêt de Saverne
  阿尔萨斯 爬山赛: Vallée de Munster Montée
stages:
  Afon Bidno - Severn: Afon Bidno - Severn
  Afon Biga - Banc Gwyn: Afon Biga - Banc Gwyn
  Afon Biga - Cwmbiga: Afon Biga - Cwmbiga
  Aghii Theodori: Aghii Theodori
  Aghii Theodori - Loutraki: Aghii Theodori - Loutraki
  Aghii Theodori Reverse: Aghii Theodori Reverse
  Banc Gwyn - Afon Biga: Banc Gwyn - Afon Biga
  Col du petit Ballon: Col du petit Ballon
  Cwmbiga - Afon Biga: Cwmbiga - Afon Biga
  Cwmbiga - Fedw Fain: Cwmbiga - Fedw Fain
  Elatia: Elatia
  Elatia - Zeli: Elatia - Zeli
  Elatia Reverse: Elatia Reverse
  Fedw Fain - Cwmbiga: Fedw Fain - Cwmbiga
  Forêt de Munster: Forêt de Munster
  Forêt de Saverne: Forêt de Saverne
  La Bollène-Vésubie - Peïra Cava: La Bollène-Vésubie - Peïra Cava
  La Bollène-Vésubie - Turini: La Bollène-Vésubie - Turini
  La traversée de La Mossig: La traversée de La Mossig
  Loutraki - Aghii Theodori: Loutraki - Aghii Theodori
  Luttenbach près Munster: Luttenbach près Munster
  Mézien - Sisteron: Mézien - Sisteron
  Mézien - St. Geniez: Mézien - St. Geniez
  New Loutraki: New Loutraki
  New Loutraki Reverse: New Loutraki Reverse
  Obersteigen: Obersteigen
  Peïra Cava - La Bollène-Vésubie: Peïra Cava - La Bollène-Vésubie
  Peïra Cava - Turini: Peïra Cava - Turini
  Pra d'Alart: Pra d'Alart
  Severn - Afon Bidno: Severn - Afon Bidno
  Sisteron - Mézien: Sisteron - Mézien
  Sisteron - St. Geniez: Sisteron - St. Geniez
  Sommet de Munster: Sommet de Munster
  Sommet de Turini: Sommet de Turini
  St. Geniez - Mézien: St. Geniez - Mézien
  St. Geniez - Sisteron: St. Geniez - Sisteron
  Steigenbach: Steigenbach
  Turini - La Bollène-Vésubie: Turini - La Bollène-Vésubie
  Turini - Peïra Cava: Turini - Peïra Cava
  Vallée de Munster Descente: Vallée de Munster Descente
  Vallée de Munster Montée: Vallée de Munster Montée
  Zeli: Zeli
  Zeli - Elatia: Zeli - Elatia
  Zeli Reverse: Zeli Reverse
